[tools]
"cargo:tex-fmt" = "latest"
"npm:json-sort-cli" = "latest"
"npm:openupm-cli" = "latest"
"pipx:radian" = "latest"
"pipx:ty" = "latest"
biome = "latest"
bun = "latest"
cargo-binstall = "latest"
ghq = "latest"
java = "latest"
node = "latest"
shellcheck = "latest"
shfmt = "latest"
usage = "latest"
uv = "latest"

[settings]
experimental = true
jobs = 10
plugin_autoupdate_last_check_duration = "1d"

[settings.cargo]
binstall = true

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true

[settings.python]
compile = true
uv_venv_auto = true

[env]
R_EXTRA_CONFIGURE_OPTIONS = "--enable-R-shlib --with-cairo"
