[tools]
"aqua:astral-sh/ty" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:biomejs/biome" = "latest"
"aqua:cargo-bins/cargo-binstall" = "latest"
"aqua:jdx/usage" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:mvdan/sh" = "latest"
"aqua:x-motemen/ghq" = "latest"
"cargo:tex-fmt" = "latest"
"core:bun" = "latest"
"core:java" = "latest"
"core:node" = "latest"
"npm:openupm-cli" = "latest"
"pipx:radian" = "latest"

[settings]
color_theme = "catppuccin"
disable_default_registry = true
experimental = true
jobs = 10
plugin_autoupdate_last_check_duration = "1d"

[settings.npm]
package_manager = "bun"

[settings.python]
compile = true
uv_venv_auto = true
