format = """
[î‚¶](#601c52)\
$os\
$username\
[î‚°](fg:#601c52 bg:#9A348E)\
$hostname\
[î‚°](fg:#9A348E bg:#DA627D)\
$directory\
[î‚°](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[î‚°](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$lua\
$nodejs\
$nim\
$python\
$rlang\
$ruby\
$rust\
$scala\
$conda\
[î‚°](fg:#86BBD8 bg:#06969A)\
$docker_context\
[î‚°](fg:#06969A bg:#33658A)\
$time\
[î‚°](fg:#33658A)
$shell\
"""
# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
disabled = false
format = "[ $user ]($style)"
show_always = true
style_root = "bg:#601c52"
style_user = "bg:#601c52"

[hostname]
format = "[$ssh_symbol]($style)[ $hostname ]($style)"
ssh_only = false
style = "bg:#9A348E"

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
disabled = false  # Disabled by default
style = "bg:#601c52"

[os.symbols]
AIX = "ï’¼ "
Alpaquita = "îª¢ "
AlmaLinux = "ïŒ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
Bluefin = "ó°¬œ "
CachyOS = "î˜ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ïŒ¢ "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ïŒ· "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ïŒ¦ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ó°£­ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ïŒ¨ "
OpenCloudOS = "â˜ï¸ "
openEuler = "ó°«ˆ "
openSUSE = "ïŒ” "
OracleLinux = "î¡™ "
Pop = "ïŒª "
Raspbian = "ïŒ• "
RedHatEnterprise = "ïŒ– "
Redhat = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ïŒ­ "
SUSE = "î½­ "
Ubuntu = "ïŒ› "
Ultramarine = "ğŸ”· "
Unknown = "î¬² "
Uos = "ğŸ² "
Void = "ïŒ® "
Windows = "î˜ª "

[shell]
bash_indicator = "î¯Š "
cmd_indicator = "î¯„ "
disabled = false
elvish_indicator = "ó°˜§ "
fish_indicator = "ó°ˆº "
format = "[ $indicator ]($style)"
ion_indicator = "î© "
nu_indicator = "nu"
powershell_indicator = "î¯‡ "
tcsh_indicator = "Tc"
unknown_indicator = "ï„  "
xonsh_indicator = "@ "
zsh_indicator = "%_"

[directory]
format = "[ $path ]($style)"
style = "bg:#DA627D"
truncation_length = 5
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

[c]
detect_extensions = ["c", "cc", "cpp", "css", "cxx", "h", "hpp", "hxx", "tcc"]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"
symbol = "î˜ "

[conda]
format = "[ $symbol $environment ]($style)"
style = "bg:#86BBD8"
symbol = "ï„Œ "

[docker_context]
format = "[ $symbol $context ]($style) $path"
style = "bg:#06969A"
symbol = "ïŒˆ "

[elixir]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"
symbol = "î‰µ "

[elm]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"
symbol = "î˜¬ "

[git_branch]
format = "[ $symbol $branch ]($style)"
style = "bg:#FCA17D"
symbol = "ï˜"

[git_status]
format = "[$all_status$ahead_behind ]($style)"
style = "bg:#FCA17D"

[golang]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"
symbol = "î˜§ "

[gradle]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"

[haskell]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"
symbol = "î· "

[java]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"
symbol = "î‰– "

[julia]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"
symbol = "î˜¤ "

[lua]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"
symbol = "î˜  "

[nodejs]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"
symbol = "îœ˜"

[nim]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"
symbol = "ó°†¥ "

[python]
detect_extensions = ["ipynb", "py", "qmd"]
format = '[ $symbol ($version)( \($virtualenv\)) ]($style)'
style = "bg:#86BBD8"
symbol = "îˆµ "

[rlang]
detect_extensions = ["R", "Rd", "Rmd", "Rproj", "Rsx", "qmd"]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"
symbol = "ó°Ÿ” "

[ruby]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"
symbol = "ó°´­ "

[rust]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"
symbol = "î¨"

[scala]
format = "[ $symbol ($version) ]($style)"
style = "bg:#86BBD8"
symbol = "îœ· "

[time]
disabled = false
format = "[ ï€„  $time ]($style)"
style = "bg:#33658A"
time_format = "%R"  # Hour:Minute Format
